### ISSUE TITLE
繁入簡出、移動端使用、全字集下生僻字候選位以及部分字拆分編碼問題

### ISSUE THREAD

**Issue by belovedrebellion** [ywxt/rime-huma#14]
1. 繁入簡出功能無法生效，即使在鍵入快捷鍵時已經顯示由「漢字」變爲「汉字」，實際打字時並未產生變化
2. 安卓端中文輸入法，將相關文件放入rime文件夾重新部署後，雖然方案已經可選「虎碼·繁」，但無法輸出漢字
3. 全字集下有時生僻字怪異地佔據了過高候選位，例如要輸入「夾」字時若處於全字集模式會發現已經被一堆生僻字擠佔到了第二頁，但「夾」本身字頻很高，不知是何原因（還有部分字也是如此，但一時想不起來具體有哪些，待補充）；詞組則是在全字集下皆會被（如果有同碼）生僻字佔據更高候選位，顯得有些違反直覺
4. 拆分編碼問題：
	1. 「徹」字拆成了〔 𫹏⺝ · WBVy 〕，虎碼中並無「𫹏」根，與此錯根錯碼相關的字也需修正
	2. 「穀」字拆成了〔 壳一禾殳 · GFXR 〕，虎碼中並無「壳」根，與此錯根錯碼相關的字也需修正
	3. 「殺」字拆成了〔 㐅木丶殳 · BEIR 〕，同樣與官方碼表不符，與此相關的字也受其影響，需修正

**Comment by ywxt** [comment]
1. 這邊在 fictx5-rime (Linux)與fcitx5-android平臺測試正常，請提供詳細的環境
2. 中文輸入法的lua插件版本過低，請將方案 `schema` 中 `lua_filter`/`lua_processor` 的`*`引用形式手動改爲 `rime.lua` 文件引入。
3. 感謝反饋常用字全集靠後的問題，目前的生成的碼表有問題。對於詞組，個人在全集使用場景主要用於生僻單字輸入，故而所有的單字都位於詞組之前。如果對此有異議，歡迎探討。
4. 這個些都是有意爲之，涉及到的字具體參見 #5 和 #8

**Comment by belovedrebellion** [comment]
### 配置問題

1. Windows 10 小狼毫 0.15.1.0
2. 非常抱歉我沒太搞懂這個引用形式具體的修改方式，schema文件中與所述相關的有如下幾行：
	1. `lua_processor@*huma.spelling_processor@spelling_processor`
	2. `lua_filter@*huma.single_char_only@single_char_only`
	3. `lua_filter@*huma.charset_filter@charset_filter`
	4. `lua_filter@*huma.spelling@spelling`
	5. `lua_filter@*huma.spelling@spelling_reverse`
	6. `lua_filter@*huma.postpone_fullcode@postpone_fullcode`

請問改爲 `rime.lua` 文件引入是怎麼樣的操作？

### 詞組與生僻字候選關係問題

常用單字優先於詞組我是認同的，但全集中生僻字也優先於詞組個人認爲並無必要，以下對實際情況進行討論：

> 如果使用者都爲純單派，那這個問題不是問題，故只討論「兼有打詞與輸入生僻字需求」用戶的情況。

1. 對於生僻字，因為本身使用頻率低，通常難以立即上屏，往往需檢視候選框确認無誤再擇定輸出；而既然都要認真查看候選框了，將那幾個詞組後置對提高輸出效率的作用微乎其微，還影響了正常的打詞。幾乎沒有需要**快速輸入大量生僻字**的場合，而詞組是可以常用的。
2. 即便退一步說，有「快速輸入大量生僻字」的要求，將生僻字優先於詞組也是意義不明的。因爲最優解是保持全字集默認開啟，不僅能隨時打生僻字，需要使生僻單字前移時開閉詞組模式即可。詞組優先於生僻單字，既不影響正常打詞，也不會影響生僻單字輸出；而反觀生僻單字優先於詞組，不僅對生僻單字本身輸入效率的影響（很可能）微乎其微，還妨礙了正常打詞。

### 拆分編碼問題

1. 很抱歉沒有認真關注那部分內容的詮釋，但我還是沒看懂「T」源字形是什麼意思，能麻煩您闡述一下嗎？
2. 還有一個字我覺得可以優化，雖然「問」的字頻高於「丁」，但「adk」敲起來手感非常舒服且符合拆分，「丁」也作爲常用字但卻要人爲多加一碼變成「add」纔能首選上屏，個人認為取官方的「ad」直接出「丁」字而僅將「問」設爲「adk」是更優解。

**Comment by ywxt** [comment]
1. 抱歉，我這邊沒有 Windows 10，但在 Windows 11上測試了 0.15.0 版本，沒有發現問題。請檢查在 `程序文件夾\data\opencc` 中是否存在 `t2s.json` 以及在 `用戶文件夾\opencc` 中是否放置其他方案的 `t2s.json`。
2. 在用戶文件夾中創建 `rime.lua` 或直接追加以下內容
```lua
spelling_processor = require('huma/spelling_processor')
spelling = require('huma/spelling')
single_char_only = require('huma/single_char_only')
charset_filter = require('huma/charset_filter')
postpone_fullcode = require('huma/postpone_fullcode')
```
然後在 `huma_trad.custom.yaml` 中添加：
```yaml
patch:
  "engine/processors/@2": lua_processor@spelling_processor
  "engine/filters/@0": lua_filter@single_char_only
  "engine/filters/@1": lua_filter@charset_filter
  "engine/filters/@5": lua_filter@spelling@spelling
  "engine/filters/@6": lua_filter@spelling@spelling_reverse
  "engine/filters/@7": lua_filter@postpone_fullcode
```

3. 如同你所說，幾乎沒有快速輸入大量生僻字的場景，大部分情況應該都是使用 `常用` 字集，`全集` 我能想到的場景就是臨時輸入個別生僻字，此時一般不會輸入詞組。~~會有人默認開啟大字集嗎？~~ 想了一下，或許某些工作會有日常錄入生僻字的需求？
4. 「T」源是臺灣字形，一方面是個人的喜好，此外就是避免如 *誤/娛* 這種右邊理論屬於同一個聲符 *吳* 但會出現不同拆分的情況。
![image](https://github.com/user-attachments/assets/6d4a771e-40c4-4af8-b85d-e12d52986d59)
![image](https://github.com/user-attachments/assets/e4a8b1df-d5f2-4aed-bc90-18c7981fcbc6)
另一種方案當然可以全部使用陸標字形，但就如我說的，個人喜好罷。
5. `問`的簡碼同意，之後我會修改。
